### ISSUE TITLE
[Meta] Xata SDK 0.24 Iteration Plan

### ISSUE THREAD

**Issue by SferaDev** [xataio/client-ts#840]
This document outlines our focused tasks for the next Xata SDK big release. It minimally indicates intent to investigate tasks or contribute to an implementation. Nothing is set in stone, but we will strive to complete these tasks in a reasonable timeframe.

*Estimated release date:* TBD
## SDK

- [ ] [Experimental] New `xata.fake` plugin to generate and import fake data
- [ ] [Experimental] New `xata.zod` plugin to get zod schema validators for a Xata schema
- [ ] [Experimental] New `xata.import` plugin to import data into Xata
- [ ] Handling undefined values in filters
  - #793
- [ ] Sort object
  - #791

## CLI

- [ ] Add `--experimental-plugins` flag to `xata codegen` command
- [ ] Compile and publish binaries

## Importer

- [ ] Revamped importer code
  - https://github.com/xataio/client-ts/pull/846

**Comment by SferaDev** [comment]
Released [SDK 0.23](https://github.com/xataio/client-ts/releases/tag/%40xata.io%2Fclient%400.21.6) and [CLI 0.11.6](https://github.com/xataio/client-ts/releases/tag/%40xata.io%2Fcli%400.11.6)

**Comment by SferaDev** [comment]
Moved to v1 iteration plan
